TC_PATH = 'D:\\Research\\totalcapture'
HM_PATH = '/home/fyhuang/data/human36'

LEARNING_RATE = 1e-5
MOMENTUM = 0.9
EPOCH_COUNT = 10
WEIGHT_DECAY = 0.0005
BATCH_SIZE = 44
TEST_BATCH = 8
PRINT_FREQ = 100
TEST_PRINT = 10
WORKER = 0
DECAY_EPOCH = 5
DECAY_RATIO = 0.2
GPU_ID = 0
